// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(

/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEXhH-oxCgf0QDCL6H2kAQp_zv3NWTeUc',
    appId: '1:357148870177:web:afd90822dadaf8117f4560',
    messagingSenderId: '357148870177',
    projectId: 'findout-9ab67',
    authDomain: 'findout-9ab67.firebaseapp.com',
    storageBucket: 'findout-9ab67.appspot.com',
    measurementId: 'G-XZFTKW7J3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbyOQhsm6NcDGyIgKZGtsH0EiiCBzEqIw',
    appId: '1:357148870177:android:1435a1f2e08bdea67f4560',
    messagingSenderId: '357148870177',
    projectId: 'findout-9ab67',
    storageBucket: 'findout-9ab67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4RSvKU3h9ozsZ7lSjY-Nk2QpHLmjOZUE',
    appId: '1:357148870177:ios:44bffefa5470bb877f4560',
    messagingSenderId: '357148870177',
    projectId: 'findout-9ab67',
    storageBucket: 'findout-9ab67.appspot.com',
    iosBundleId: 'com.example.findOutFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4RSvKU3h9ozsZ7lSjY-Nk2QpHLmjOZUE',
    appId: '1:357148870177:ios:44bffefa5470bb877f4560',
    messagingSenderId: '357148870177',
    projectId: 'findout-9ab67',
    storageBucket: 'findout-9ab67.appspot.com',
    iosBundleId: 'com.example.findOutFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEXhH-oxCgf0QDCL6H2kAQp_zv3NWTeUc',
    appId: '1:357148870177:web:7214e4e6215095c17f4560',
    messagingSenderId: '357148870177',
    projectId: 'findout-9ab67',
    authDomain: 'findout-9ab67.firebaseapp.com',
    storageBucket: 'findout-9ab67.appspot.com',
    measurementId: 'G-28TC600GD4',
  );
}
